on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
      build_dep:
        type: string
        default: ""
jobs:
  source:
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.tag.outputs.pkg }}
      version: ${{ steps.tag.outputs.version }}
      skip: ${{ steps.tag.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - name: resolve container digest
        run: |
          set -o noclobber
          image="ghcr.io/gardenlinux/repo-debian-snapshot"
          podman pull "$image"
          digest="$(podman image inspect --format '{{ .Digest }}' "$image")"
          echo "$image@$digest" > .container
      - name: set release version suffix
        if: inputs.release
        run: |
          echo 'version_suffix=gardenlinux0' >> prepare_source
      - name: commit
        run: |
          git checkout --detach HEAD
          git add .
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: build source pkg
        run: |
          dir="$(mktemp -d)"
          git clone --depth=1 https://github.com/gardenlinux/package-build "$dir/package-build"
          "$dir/package-build/build" --source-only .
      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: |
            .
            !.git
      - id: tag
        name: check version
        run: |
          ls -lah .build
          pkg="$(awk -F ': ' '$1 == "Source" { print $2 }' < .build/*.dsc)"
          version="$(awk -F ': ' '$1 == "Version" { print $2 }' < .build/*.dsc | tr '~' '+')"
          version="${version#*:}"
          echo "pkg=$pkg" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          if [[ "$version" != *"~dev" ]]; then
            git fetch --tags
            if git rev-list "$version" > /dev/null 2>&1; then
              echo "$version already exists"
              echo skip=true >> "$GITHUB_OUTPUT"
            else
              git tag "$version"
              git push origin "$version"
            fi
          fi
  binary:
    runs-on: ubuntu-latest
    needs: source
    if: ${{ ! needs.source.outputs.skip }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - name: setup binfmt
        if: matrix.arch == 'arm64'
        run: sudo podman run --privileged ghcr.io/gardenlinux/binfmt_container
      - uses: actions/download-artifact@v4
        with:
          name: source
      - name: fetch build dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir build_dep
          while read repo tag; do
            if [ -n "$repo" ] && [ -n "$tag" ]; then
              gh release download --dir build_dep --repo "$repo" "$tag"
            fi
          done <<< "$(cat << 'EOF'
          ${{ inputs.build_dep }}
          EOF
          )"
      - name: build binary pkg
        run: |
          dir="$(mktemp -d)"
          git clone --depth=1 https://github.com/gardenlinux/package-build "$dir/package-build"
          arch="${{ matrix.arch }}"
          build=binary
          if [ "$arch" = arm64 ]; then
            build=any
          fi
          "$dir/package-build/build" --binary-only --arch "$arch" --build "$build" .
      - uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.arch }}
          path: .build
  release:
    runs-on: ubuntu-latest
    needs: [ source, binary ]
    if: inputs.release && ! needs.source.outputs.skip
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binary-amd64
          path: .build
      - uses: actions/download-artifact@v4
        with:
          name: binary-arm64
          path: .build
      - name: publish release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -lah .build
          pkg="${{ needs.source.outputs.pkg }}"
          version="${{ needs.source.outputs.version }}"
          gh release create "$version" --verify-tag --title "${pkg}_${version}" --notes "created by GitHub actions run [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" .build/*
